kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "go-echo.labels" . | nindent 4 }}
    openservicemesh.io/monitored-by: osm
    kubernetes.azure.com/generator: draft
  annotations:
    openservicemesh.io/sidecar-injection: enabled

