apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo
  labels:
    app: go-echo
    kubernetes.azure.com/generator: draft
  namespace: default
spec:
  selector:
    matchLabels:
      app: go-echo
  template:
    spec:
      containers:
        - name: go-echo
          image: go-echo:latest