apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-echo
    kubernetes.azure.com/generator: draft
  name: go-echo
  namespace: default
spec:
  selector:
    matchLabels:
      app: go-echo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: goechoacr.azurecr.io/go-echo-kustomize
        name: go-echo
        resources: {}
status: {}
