apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-echo
    kubernetes.azure.com/generator: draft
  name: go-echo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-echo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-echo
    spec:
      containers:
      - image: meeceacr.azurecr.io/sample/hello-world
        imagePullPolicy: Always
        name: go-echo
        ports:
        - containerPort: 1323
        resources: {}
status: {}
